import commonjs from '@rollup/plugin-commonjs'
import external from 'rollup-plugin-peer-deps-external'
import postcss from 'rollup-plugin-postcss'
import resolve from '@rollup/plugin-node-resolve'
import esbuild from 'rollup-plugin-esbuild'
import filesize from 'rollup-plugin-filesize'
import progress from 'rollup-plugin-progress'
import json from '@rollup/plugin-json'

/** @type { import('rollup').RollupOptions } */
const config = {
  input: 'src/index.tsx',
  output: {
    file: './dist/index.js',
    format: 'umd',
    name: 'ReactCheatsheets',
    exports: 'named',
    sourcemap: true,
    globals: {
      'object-assign': 'objAssign',
      react: 'react',
      'react-dom': 'reactDOM',
      'react-beautiful-dnd': 'ReactBeautifulDND',
      'react-syntax-highlighter': 'ReactSyntaxHighlighter',
      'react-syntax-highlighter/dist/esm/styles/prism': 'prismStylesheet',
      refractor: 'refractor',
    },
  },
  external: ['@babel/runtime/helpers/interopRequireDefault'],
  plugins: [
    json(),
    filesize(),
    progress(),
    resolve({
      browser: true,
      extensions: ['.js', '.ts'],
    }),
    commonjs({
      sourceMap: false,
    }),
    external(),
    postcss({
      modules: true,
    }),
    esbuild({
      exclude: /node_modules/,
      include: ['./src/**/*'],
      loaders: {
        '.js': 'js',
        '.ts': 'ts',
        '.tsx': 'tsx',
      },
      minify: process.env.NODE_ENV !== 'development',
      minifyIdentifiers: false,
      sourceMap: true,
      target: 'es2017',
    }),
  ],
}

export default config

function getStylesheets() {
  return [
    'highlight.js/lib/languages/accesslog',
    'highlight.js/lib/languages/ada',
    'highlight.js/lib/languages/1c',
    'highlight.js/lib/languages/abnf',
    'highlight.js/lib/languages/angelscript',
    'highlight.js/lib/languages/actionscript',
    'highlight.js/lib/languages/apache',
    'highlight.js/lib/languages/applescript',
    'highlight.js/lib/languages/armasm',
    'highlight.js/lib/languages/autoit',
    'highlight.js/lib/languages/arcade',
    'highlight.js/lib/languages/arduino',
    'highlight.js/lib/languages/aspectj',
    'highlight.js/lib/languages/autohotkey',
    'highlight.js/lib/languages/axapta',
    'highlight.js/lib/languages/avrasm',
    'highlight.js/lib/languages/awk',
    'highlight.js/lib/languages/cal',
    'highlight.js/lib/languages/asciidoc',
    'highlight.js/lib/languages/bash',
    'highlight.js/lib/languages/brainfuck',
    'highlight.js/lib/languages/ceylon',
    'highlight.js/lib/languages/c (imported',
    'highlight.js/lib/languages/capnproto',
    'highlight.js/lib/languages/clojure',
    'highlight.js/lib/languages/coq',
    'highlight.js/lib/languages/cmake',
    'highlight.js/lib/languages/clojure',
    'highlight.js/lib/languages/csharp',
    'highlight.js/lib/languages/c-like',
    'highlight.js/lib/languages/cpp',
    'highlight.js/lib/languages/coffeescript',
    'highlight.js/lib/languages/css',
    'highlight.js/lib/languages/crmsh',
    'highlight.js/lib/languages/d (imported',
    'highlight.js/lib/languages/dns',
    'highlight.js/lib/languages/clean',
    'highlight.js/lib/languages/delphi',
    'highlight.js/lib/languages/crystal',
    'highlight.js/lib/languages/cos',
    'highlight.js/lib/languages/django',
    'highlight.js/lib/languages/dart',
    'highlight.js/lib/languages/basic',
    'highlight.js/lib/languages/dockerfile',
    'highlight.js/lib/languages/dts',
    'highlight.js/lib/languages/dos',
    'highlight.js/lib/languages/elm',
    'highlight.js/lib/languages/dust',
    'highlight.js/lib/languages/ebnf',
    'highlight.js/lib/languages/erlang',
    'highlight.js/lib/languages/elixir',
    'highlight.js/lib/languages/diff',
    'highlight.js/lib/languages/excel',
    'highlight.js/lib/languages/dsconfig',
    'highlight.js/lib/languages/erlang',
    'highlight.js/lib/languages/erb',
    'highlight.js/lib/languages/flix',
    'highlight.js/lib/languages/fortran',
    'highlight.js/lib/languages/fix',
    'highlight.js/lib/languages/glsl',
    'highlight.js/lib/languages/gams',
    'highlight.js/lib/languages/gherkin',
    'highlight.js/lib/languages/fsharp',
    'highlight.js/lib/languages/gauss',
    'highlight.js/lib/languages/handlebars',
    'highlight.js/lib/languages/groovy',
    'highlight.js/lib/languages/gcode',
    'highlight.js/lib/languages/go',
    'highlight.js/lib/languages/golo',
    'highlight.js/lib/languages/gradle',
    'highlight.js/lib/languages/haskell',
    'highlight.js/lib/languages/gml',
    'highlight.js/lib/languages/haxe',
    'highlight.js/lib/languages/hsp',
    'highlight.js/lib/languages/haml',
    'highlight.js/lib/languages/htmlbars',
    'highlight.js/lib/languages/http',
    'highlight.js/lib/languages/hy',
    'highlight.js/lib/languages/ini',
    'highlight.js/lib/languages/isbl',
    'highlight.js/lib/languages/javascript',
    'highlight.js/lib/languages/inform7',
    'highlight.js/lib/languages/irpf90',
    'highlight.js/lib/languages/julia',
    'highlight.js/lib/languages/jboss',
    'highlight.js/lib/languages/julia',
    'highlight.js/lib/languages/java',
    'highlight.js/lib/languages/kotlin',
    'highlight.js/lib/languages/json',
    'highlight.js/lib/languages/leaf',
    'highlight.js/lib/languages/latex',
    'highlight.js/lib/languages/ldif',
    'highlight.js/lib/languages/lasso',
    'highlight.js/lib/languages/lsl',
    'highlight.js/lib/languages/lisp',
    'highlight.js/lib/languages/livecodeserver',
    'highlight.js/lib/languages/livescript',
    'highlight.js/lib/languages/markdown',
    'highlight.js/lib/languages/less',
    'highlight.js/lib/languages/lua',
    'highlight.js/lib/languages/llvm',
    'highlight.js/lib/languages/mercury',
    'highlight.js/lib/languages/makefile',
    'highlight.js/lib/languages/matlab',
    'highlight.js/lib/languages/mathematica',
    'highlight.js/lib/languages/monkey',
    'highlight.js/lib/languages/mojolicious',
    'highlight.js/lib/languages/maxima',
    'highlight.js/lib/languages/mel',
    'highlight.js/lib/languages/mipsasm',
    'highlight.js/lib/languages/moonscript',
    'highlight.js/lib/languages/n1ql',
    'highlight.js/lib/languages/mizar',
    'highlight.js/lib/languages/nginx',
    'highlight.js/lib/languages/objectivec',
    'highlight.js/lib/languages/nix',
    'highlight.js/lib/languages/nsis',
    'highlight.js/lib/languages/openscad',
    'highlight.js/lib/languages/bnf',
    'highlight.js/lib/languages/ocaml',
    'highlight.js/lib/languages/node',
    'highlight.js/lib/languages/oxygene',
    'highlight.js/lib/languages/perl',
    'highlight.js/lib/languages/pf',
    'highlight.js/lib/languages/pony',
    'highlight.js/lib/languages/pgsql',
    'highlight.js/lib/languages/php',
    'highlight.js/lib/languages/plaintext',
    'highlight.js/lib/languages/php',
    'highlight.js/lib/languages/properties',
    'highlight.js/lib/languages/parser3',
    'highlight.js/lib/languages/prolog',
    'highlight.js/lib/languages/profile',
    'highlight.js/lib/languages/python',
    'highlight.js/lib/languages/puppet',
    'highlight.js/lib/languages/python',
    'highlight.js/lib/languages/processing',
    'highlight.js/lib/languages/purebasic',
    'highlight.js/lib/languages/qml',
    'highlight.js/lib/languages/q (imported',
    'highlight.js/lib/languages/powershell',
    'highlight.js/lib/languages/reasonml',
    'highlight.js/lib/languages/nim',
    'highlight.js/lib/languages/roboconf',
    'highlight.js/lib/languages/rib',
    'highlight.js/lib/languages/rsl',
    'highlight.js/lib/languages/r (imported',
    'highlight.js/lib/languages/ruleslanguage',
    'highlight.js/lib/languages/rust',
    'highlight.js/lib/languages/scilab',
    'highlight.js/lib/languages/sas',
    'highlight.js/lib/languages/ruby',
    'highlight.js/lib/languages/scheme',
    'highlight.js/lib/languages/shell',
    'highlight.js/lib/languages/scala',
    'highlight.js/lib/languages/smalltalk',
    'highlight.js/lib/languages/sml',
    'highlight.js/lib/languages/scss',
    'highlight.js/lib/languages/smali',
    'highlight.js/lib/languages/sql',
    'highlight.js/lib/languages/sqf',
    'highlight.js/lib/languages/stan',
    'highlight.js/lib/languages/swift',
    'highlight.js/lib/languages/stata',
    'highlight.js/lib/languages/step21',
    'highlight.js/lib/languages/stylus',
    'highlight.js/lib/languages/subunit',
    'highlight.js/lib/languages/tp',
    'highlight.js/lib/languages/tap',
    'highlight.js/lib/languages/tcl',
    'highlight.js/lib/languages/taggerscript',
    'highlight.js/lib/languages/thrift',
    'highlight.js/lib/languages/typescript',
    'highlight.js/lib/languages/twig',
    'highlight.js/lib/languages/vbscript',
    'highlight.js/lib/languages/vbnet',
    'highlight.js/lib/languages/vhdl',
    'highlight.js/lib/languages/vbscript',
    'highlight.js/lib/languages/x86asm',
    'highlight.js/lib/languages/vala',
    'highlight.js/lib/languages/xml',
    'highlight.js/lib/languages/verilog',
    'highlight.js/lib/languages/vim',
    'highlight.js/lib/languages/yaml',
    'highlight.js/lib/languages/xl',
    'highlight.js/lib/languages/xquery',
    'highlight.js/lib/languages/csp',
    'highlight.js/lib/languages/zephir',
    'highlight.js/lib/languages/routeros',
    'highlight.js/lib/languages/protobuf',
  ]
}
